In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("pre-owned cars.csv")

In [ ]:
df.head()

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,01-01-2021,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,01-07-2018,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,Manual,2022.0,01-08-2022,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,01-04-2023,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,Manual,2021.0,01-07-2021,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL

In [ ]:
df.shape

(2806, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2806 entries, 0 to 2805
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                2805 non-null   object
 1   model                2805 non-null   object
 2   transmission         2805 non-null   object
 3   make_year            2805 non-null   float64
 4   reg_year             720 non-null    object
 5   fuel_type            2805 non-null   object
 6   engine_capacity(CC)  2688 non-null   float64
 7   km_driven            2805 non-null   float64
 8   ownership            2805 non-null   object
 9   price                2806 non-null   int64
 10  overall_cost         2805 non-null   float64
 11  has_insurance        2805 non-null   object
 12  spare_key            2805 non-null   object
 13  reg_number           2805 non-null   object
 14  title                2805 non-null   object
dtypes: float64(4), int64(1), object(10)
memory usage: 329.0+ KB

In [ ]:
df.describe()

,make_year,engine_capacity(CC),km_driven,price,overall_cost
count,2805.000000,2688.000000,2805.000000,2.806000e+03,2805.000000
mean,2018.181105,1259.027530,49215.477362,1.342522e+06,13495.022816
std,2.945293,254.504798,26626.932696,3.554669e+07,6040.809220
min,2010.000000,624.000000,450.000000,1.630000e+05,4039.000000
25%,2016.000000,1194.000000,28540.000000,4.350000e+05,9267.000000
50%,2018.000000,1197.000000,45695.000000,5.940000e+05,12145.000000
75%,2021.000000,1462.000000,68182.000000,8.140000e+05,15760.000000
max,2024.000000,2694.000000,143991.000000,1.883558e+09,47338.000000

In [ ]:
df.brand.value_counts()

brand
Maruti        925
Hyundai       660
Honda         276
Tata          240
Renault       167
KIA           116
Mahindra      114
Ford           64
Volkswagen     53
Nissan         38
MG             37
Toyota         36
Datsun         34
Skoda          33
Jeep           12
Name: count, dtype: int64

In [ ]:
df.drop("reg_year",axis=1,inplace = True)

In [ ]:
df

,brand,model,transmission,make_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,Manual,2022.0,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,Manual,2021.0,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2801,Ford,Ecosport TREND + 1.5L PETROL AT,Automatic,2018.0,Petrol,1497.0,46982.0,1st owner,661000,12920.0,True,Yes,MH03,2018 Ford Ecosport TREND + 1.5L PETROL AT
2802,Honda,Jazz 1.2L I-VTEC V,Manual,2015.0,Petrol,1199.0,38706.0,2nd owner,412000,8057.0,True,Yes,MH01,2015 Honda Jazz 1.2L I-VTEC V
2803,Hyundai,Elite i20 MAGNA 1.2,Manual,2016.0,Petrol,1197.0,31405.0,1st owner,496000,9704.0,True,Yes,MH03,2016 Hyundai Elite i20 MAGNA 1.2
2804,Maruti,Baleno DELTA PETROL 1.2,Manual,2017.0,Petrol,1197.0,47676.0,1st owner,509000,9959.0,True,Yes,MH04,2017 Maruti Baleno DELTA PETROL 1.2
2805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1883558000,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.loc[:,"transmission"] == "Automatic"

0       False
1       False
2       False
3        True
4       False
        ...
2801     True
2802    False
2803    False
2804    False
2805    False
Name: transmission, Length: 2806, dtype: bool

In [ ]:
df.loc[df.loc[:,"transmission"] == "Automatic"]

,brand,model,transmission,make_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
7,Tata,NEXON XMA DIESEL,Automatic,2020.0,Diesel,NaN,59866.0,1st owner,728000,14228.0,True,No,DL5C,2020 Tata NEXON XMA DIESEL
8,Mahindra,XUV700 AX 7 LUXURY D AWD AT 7 STR,Automatic,2022.0,Diesel,2184.0,62567.0,1st owner,2322000,44197.0,True,No,DL10,2022 Mahindra XUV700 AX 7 LUXURY D AWD AT 7 STR
9,Ford,Ecosport TITANIUM + 1.5L PETROL AT,Automatic,2019.0,Petrol,1497.0,58503.0,1st owner,766000,14977.0,True,No,DL10,2019 Ford Ecosport TITANIUM + 1.5L PETROL AT
16,Maruti,Alto K10 VXI AMT,Automatic,2014.0,Petrol,998.0,71297.0,1st owner,265000,5901.0,True,No,DL3C,2014 Maruti Alto K10 VXI AMT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795,Tata,NEXON FEARLESS + SUNROOF DCA DUAL TONE 1.2 PETROL,Automatic,2024.0,Petrol,NaN,11540.0,1st owner,1399000,26629.0,True,Yes,MH46,2024 Tata NEXON FEARLESS + SUNROOF DCA DUAL TO...
2797,Hyundai,NEW I20 ASTA 1.2 AT,Automatic,2021.0,Petrol,1197.0,15831.0,1st owner,831000,15817.0,True,Yes,MH05,2021 Hyundai NEW I20 ASTA 1.2 AT
2798,Hyundai,NEW SANTRO SPORTZ AMT,Automatic,2019.0,Petrol,1086.0,56370.0,2nd owner,396000,7732.0,True,Yes,MH48,2019 Hyundai NEW SANTRO SPORTZ AMT
2799,Maruti,IGNIS DELTA 1.2 AMT,Automatic,2017.0,Petrol,1197.0,80035.0,1st owner,428000,8377.0,True,No,MH01,2017 Maruti IGNIS DELTA 1.2 AMT
2801,Ford,Ecosport TREND + 1.5L PETROL AT,Automatic,2018.0,Petrol,1497.0,46982.0,1st owner,661000,12920.0,True,Yes,MH03,2018 Ford Ecosport TREND + 1.5L PETROL AT

In [ ]:
df.loc[(df.loc[:,"transmission"] == "Automatic")  & (df.loc[:,"fuel_type"] == "Electric") & (df.loc[:,"km_driven"] >50000)]

,brand,model,transmission,make_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
623,Tata,NEXON EV XZ PLUS,Automatic,2022.0,Electric,NaN,56728.0,1st owner,1350000,25696.0,True,Yes,DL7G,2022 Tata NEXON EV XZ PLUS

In [ ]:
df.to_csv("pre_owned1.csv")