In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [5]:
df.shape

(891, 12)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
df.Age.value_counts()

Age
24.00    30
22.00    27
18.00    26
28.00    25
19.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [10]:
df.drop("Cabin",axis=1,inplace=True)

In [11]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [12]:
df.Name.value_counts()

Name
Braund, Mr. Owen Harris                                1
Cumings, Mrs. John Bradley (Florence Briggs Thayer)    1
Heikkinen, Miss. Laina                                 1
Futrelle, Mrs. Jacques Heath (Lily May Peel)           1
Allen, Mr. William Henry                               1
                                                      ..
Montvila, Rev. Juozas                                  1
Graham, Miss. Margaret Edith                           1
Johnston, Miss. Catherine Helen "Carrie"               1
Behr, Mr. Karl Howell                                  1
Dooley, Mr. Patrick                                    1
Name: count, Length: 891, dtype: int64

In [41]:
new = df.Name.str.split(",").str[1].str.split(".").str[0].str.strip()

In [42]:

new

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: Name, Length: 891, dtype: object

In [15]:
df.insert(4,"title",new)

In [16]:
df.head()

,PassengerId,Survived,Pclass,Name,title,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Mr,male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mrs,female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",Miss,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mrs,female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",Mr,male,35.0,0,0,373450,8.0500,S

In [17]:
mr_df = df[df.loc[:,"title"] == "Mr"]

In [18]:
mr_df

,PassengerId,Survived,Pclass,Name,title,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Mr,male,22.0,1,0,A/5 21171,7.2500,S
4,5,0,3,"Allen, Mr. William Henry",Mr,male,35.0,0,0,373450,8.0500,S
5,6,0,3,"Moran, Mr. James",Mr,male,NaN,0,0,330877,8.4583,Q
6,7,0,1,"McCarthy, Mr. Timothy J",Mr,male,54.0,0,0,17463,51.8625,S
12,13,0,3,"Saundercock, Mr. William Henry",Mr,male,20.0,0,0,A/5. 2151,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...,...
881,882,0,3,"Markun, Mr. Johann",Mr,male,33.0,0,0,349257,7.8958,S
883,884,0,2,"Banfield, Mr. Frederick James",Mr,male,28.0,0,0,C.A./SOTON 34068,10.5000,S
884,885,0,3,"Sutehall, Mr. Henry Jr",Mr,male,25.0,0,0,SOTON/OQ 392076,7.0500,S
889,890,1,1,"Behr, Mr. Karl Howell",Mr,male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",Mr,male,32.0,0,0,370376,7.7500,Q

In [19]:
mean = mr_df.Age.mean()

In [20]:
mean

np.float64(32.368090452261306)

In [21]:
mr_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
title            0
Sex              0
Age            119
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
dtype: int64

In [22]:
mr_index = mr_df[mr_df.Age.isnull()].index

In [23]:
mr_index

Index([  5,  17,  26,  29,  36,  42,  45,  46,  48,  55,
       ...
       825, 826, 828, 832, 837, 839, 846, 859, 868, 878],
      dtype='int64', length=119)

In [24]:
df.loc[mr_index,'Age'] = mean

In [25]:
df.head(10)

,PassengerId,Survived,Pclass,Name,title,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Mr,male,22.00000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mrs,female,38.00000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",Miss,female,26.00000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mrs,female,35.00000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",Mr,male,35.00000,0,0,373450,8.0500,S
5,6,0,3,"Moran, Mr. James",Mr,male,32.36809,0,0,330877,8.4583,Q
6,7,0,1,"McCarthy, Mr. Timothy J",Mr,male,54.00000,0,0,17463,51.8625,S
7,8,0,3,"Palsson, Master. Gosta Leonard",Master,male,2.00000,3,1,349909,21.0750,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Mrs,female,27.00000,0,2,347742,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Mrs,female,14.00000,1,0,237736,30.0708,C

In [26]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
title           0
Sex             0
Age            58
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        2
dtype: int64

In [27]:
miss_df = df[df.loc[:,"title"]=="Miss"]

In [28]:
miss_df

,PassengerId,Survived,Pclass,Name,title,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",Miss,female,26.0,0,0,STON/O2. 3101282,7.9250,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",Miss,female,4.0,1,1,PP 9549,16.7000,S
11,12,1,1,"Bonnell, Miss. Elizabeth",Miss,female,58.0,0,0,113783,26.5500,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",Miss,female,14.0,0,0,350406,7.8542,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",Miss,female,15.0,0,0,330923,8.0292,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
866,867,1,2,"Duran y More, Miss. Asuncion",Miss,female,27.0,1,0,SC/PARIS 2149,13.8583,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",Miss,female,15.0,0,0,2667,7.2250,C
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",Miss,female,22.0,0,0,7552,10.5167,S
887,888,1,1,"Graham, Miss. Margaret Edith",Miss,female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Miss,female,NaN,1,2,W./C. 6607,23.4500,S

In [29]:
mean_miss=miss_df.Age.mean()

In [30]:
mean_miss

np.float64(21.773972602739725)

In [31]:
miss_df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
title           0
Sex             0
Age            36
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        1
dtype: int64

In [32]:
miss_index= miss_df[miss_df.Age.isnull()].index

In [33]:
miss_index

Index([ 28,  32,  47,  82, 109, 128, 180, 198, 229, 235, 240, 241, 264, 274,
       300, 303, 306, 330, 358, 359, 368, 409, 485, 502, 564, 573, 593, 596,
       612, 653, 680, 697, 727, 792, 863, 888],
      dtype='int64')

In [34]:
df.loc[miss_index,"Age"]=mean_miss

In [35]:
df.head()

,PassengerId,Survived,Pclass,Name,title,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Mr,male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mrs,female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",Miss,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mrs,female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",Mr,male,35.0,0,0,373450,8.0500,S

In [36]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
title           0
Sex             0
Age            22
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        2
dtype: int64

In [37]:
df.title.value_counts()

title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Major             2
Mlle              2
Col               2
Don               1
Mme               1
Ms                1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64