In [1]:
import pandas as pd

In [2]:
data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    "Customer": ["Amit", "Neha", "Rahul", "Simran", "Karan", "Isha", "Mohit", "Priya", "Arjun", "Meera"],
    "Amount": [2500, 1800, 3200, 1500, 2700, 2100, 3500, 2900, 1700, 2600],
    "Order_Date": [
        "2026-02-01", "2026-02-02", "2026-02-03", "2026-02-04", "2026-02-05",
        "2026-02-06", "2026-02-07", "2026-02-08", "2026-02-09", "2026-02-10"
    ]
}

df= pd.DataFrame(data)
df

   Order_ID Customer  Amount  Order_Date
0      1001     Amit    2500  2026-02-01
1      1002     Neha    1800  2026-02-02
2      1003    Rahul    3200  2026-02-03
3      1004   Simran    1500  2026-02-04
4      1005    Karan    2700  2026-02-05
5      1006     Isha    2100  2026-02-06
6      1007    Mohit    3500  2026-02-07
7      1008    Priya    2900  2026-02-08
8      1009    Arjun    1700  2026-02-09
9      1010    Meera    2600  2026-02-10

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    10 non-null     int64
 1   Customer    10 non-null     object
 2   Amount      10 non-null     int64
 3   Order_Date  10 non-null     object
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [6]:
df.Order_Date= pd.to_datetime(df.Order_Date)
df

   Order_ID Customer  Amount Order_Date
0      1001     Amit    2500 2026-02-01
1      1002     Neha    1800 2026-02-02
2      1003    Rahul    3200 2026-02-03
3      1004   Simran    1500 2026-02-04
4      1005    Karan    2700 2026-02-05
5      1006     Isha    2100 2026-02-06
6      1007    Mohit    3500 2026-02-07
7      1008    Priya    2900 2026-02-08
8      1009    Arjun    1700 2026-02-09
9      1010    Meera    2600 2026-02-10

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    10 non-null     int64
 1   Customer    10 non-null     object
 2   Amount      10 non-null     int64
 3   Order_Date  10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 452.0+ bytes

In [9]:
df.loc[:,'Year']= df.loc[:,'Order_Date'].dt.year

In [10]:
df

   Order_ID Customer  Amount Order_Date  Year
0      1001     Amit    2500 2026-02-01  2026
1      1002     Neha    1800 2026-02-02  2026
2      1003    Rahul    3200 2026-02-03  2026
3      1004   Simran    1500 2026-02-04  2026
4      1005    Karan    2700 2026-02-05  2026
5      1006     Isha    2100 2026-02-06  2026
6      1007    Mohit    3500 2026-02-07  2026
7      1008    Priya    2900 2026-02-08  2026
8      1009    Arjun    1700 2026-02-09  2026
9      1010    Meera    2600 2026-02-10  2026

In [13]:
df.loc[:,'Day_Name']= df.loc[:,'Order_Date'].dt.day_name()

In [14]:
df

   Order_ID Customer  Amount Order_Date  Year   Day_Name
0      1001     Amit    2500 2026-02-01  2026     Sunday
1      1002     Neha    1800 2026-02-02  2026     Monday
2      1003    Rahul    3200 2026-02-03  2026    Tuesday
3      1004   Simran    1500 2026-02-04  2026  Wednesday
4      1005    Karan    2700 2026-02-05  2026   Thursday
5      1006     Isha    2100 2026-02-06  2026     Friday
6      1007    Mohit    3500 2026-02-07  2026   Saturday
7      1008    Priya    2900 2026-02-08  2026     Sunday
8      1009    Arjun    1700 2026-02-09  2026     Monday
9      1010    Meera    2600 2026-02-10  2026    Tuesday

In [ ]:
df.loc[:,'Month']= df.loc[:,'Order_Date'].dt.month_name()  # month, month_name()

C:\Users\hp\AppData\Local\Temp\ipykernel_16440\167677413.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['February' 'February' 'February' 'February' 'February' 'February'
 'February' 'February' 'February' 'February']' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  df.loc[:,'Month']= df.loc[:,'Order_Date'].dt.month_name()

In [18]:
df

   Order_ID Customer  Amount Order_Date  Year   Day_Name     Month
0      1001     Amit    2500 2026-02-01  2026     Sunday  February
1      1002     Neha    1800 2026-02-02  2026     Monday  February
2      1003    Rahul    3200 2026-02-03  2026    Tuesday  February
3      1004   Simran    1500 2026-02-04  2026  Wednesday  February
4      1005    Karan    2700 2026-02-05  2026   Thursday  February
5      1006     Isha    2100 2026-02-06  2026     Friday  February
6      1007    Mohit    3500 2026-02-07  2026   Saturday  February
7      1008    Priya    2900 2026-02-08  2026     Sunday  February
8      1009    Arjun    1700 2026-02-09  2026     Monday  February
9      1010    Meera    2600 2026-02-10  2026    Tuesday  February

In [36]:
d= pd.read_csv('2023_Countries by Population.csv')
d

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.514994e+09,1.670491e+09,India,3287590.00,2973190.00,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.415606e+09,1.312636e+09,China,9706961.00,9424702.90,CN,CHN,-0.0113,-0.0002,0.1781,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.521623e+08,3.753920e+08,United States,9372610.00,9147420.00,US,USA,0.0581,0.0050,0.0425,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.00,1877519.00,ID,IDN,0.0727,0.0074,0.0347,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.740298e+08,3.678085e+08,Pakistan,881912.00,770880.00,PK,PAK,0.1495,0.0198,0.0300,311.9625,807.9829,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,500,11452.0,5.138000e+03,4.938000e+03,4.390000e+03,4.386000e+03,4.301000e+03,3.781000e+03,Montserrat,102.00,102.00,MS,MSR,NaN,-0.0009,NaN,43.0000,111.3700,230
230,238,2240.0,3.080000e+03,3.187000e+03,3.780000e+03,3.791000e+03,3.869000e+03,3.779000e+03,Falkland Islands,12173.00,12173.00,FK,FLK,NaN,0.0029,NaN,0.3114,0.8066,231
231,570,3637.0,2.074000e+03,1.812000e+03,1.934000e+03,1.935000e+03,1.948000e+03,2.096000e+03,Niue,261.00,261.00,NU,NIU,0.0000,0.0005,NaN,7.4138,19.2017,232
232,772,1647.0,1.666000e+03,1.367000e+03,1.871000e+03,1.893000e+03,2.046000e+03,2.430000e+03,Tokelau,12.00,10.00,TK,TKL,NaN,0.0118,NaN,189.3000,490.2870,233
233,336,733.0,6.510000e+02,5.960000e+02,5.100000e+02,5.180000e+02,5.610000e+02,7.310000e+02,Vatican City,0.44,0.44,VA,VAT,NaN,0.0157,NaN,1177.2727,3049.1364,234

In [37]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   place            234 non-null    int64
 1   pop1980          234 non-null    float64
 2   pop2000          234 non-null    float64
 3   pop2010          234 non-null    float64
 4   pop2022          234 non-null    float64
 5   pop2023          234 non-null    float64
 6   pop2030          234 non-null    float64
 7   pop2050          234 non-null    float64
 8   country          234 non-null    object
 9   area             234 non-null    float64
 10  landAreaKm       234 non-null    float64
 11  cca2             233 non-null    object
 12  cca3             234 non-null    object
 13  netChange        226 non-null    float64
 14  growthRate       234 non-null    float64
 15  worldPercentage  228 non-null    float64
 16  density          234 non-null    float64
 17  densityMi        234 non-null    float64
 18  rank             234 non-null    int64
dtypes: float64(14), int64(2), object(3)
memory usage: 34.9+ KB

In [38]:
d.isnull().sum()

place              0
pop1980            0
pop2000            0
pop2010            0
pop2022            0
pop2023            0
pop2030            0
pop2050            0
country            0
area               0
landAreaKm         0
cca2               1
cca3               0
netChange          8
growthRate         0
worldPercentage    6
density            0
densityMi          0
rank               0
dtype: int64

In [39]:
pop26=(d.loc[:,'pop2023']*d.loc[:,'growthRate'])*3

In [40]:
p26= d.loc[:,'pop2023']+pop26

In [41]:
d.insert(6, column='pop2026', value=p26)

In [43]:
d.loc[:,'pop2023']-(d.loc[:,'pop2023']*d.loc[:,'growthRate'])

0      1.417056e+09
1      1.425956e+09
2      3.382966e+08
3      2.754804e+08
4      2.357240e+08
           ...
229    4.389947e+03
230    3.780006e+03
231    1.934033e+03
232    1.870663e+03
233    5.098674e+02
Length: 234, dtype: float64

In [42]:
d

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2026,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.463343e+09,1.514994e+09,1.670491e+09,India,3287590.00,2973190.00,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.424816e+09,1.415606e+09,1.312636e+09,China,9706961.00,9424702.90,CN,CHN,-0.0113,-0.0002,0.1781,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.450965e+08,3.521623e+08,3.753920e+08,United States,9372610.00,9147420.00,US,USA,0.0581,0.0050,0.0425,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.836954e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.00,1877519.00,ID,IDN,0.0727,0.0074,0.0347,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.547705e+08,2.740298e+08,3.678085e+08,Pakistan,881912.00,770880.00,PK,PAK,0.1495,0.0198,0.0300,311.9625,807.9829,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,500,11452.0,5.138000e+03,4.938000e+03,4.390000e+03,4.386000e+03,4.374158e+03,4.301000e+03,3.781000e+03,Montserrat,102.00,102.00,MS,MSR,NaN,-0.0009,NaN,43.0000,111.3700,230
230,238,2240.0,3.080000e+03,3.187000e+03,3.780000e+03,3.791000e+03,3.823982e+03,3.869000e+03,3.779000e+03,Falkland Islands,12173.00,12173.00,FK,FLK,NaN,0.0029,NaN,0.3114,0.8066,231
231,570,3637.0,2.074000e+03,1.812000e+03,1.934000e+03,1.935000e+03,1.937902e+03,1.948000e+03,2.096000e+03,Niue,261.00,261.00,NU,NIU,0.0000,0.0005,NaN,7.4138,19.2017,232
232,772,1647.0,1.666000e+03,1.367000e+03,1.871000e+03,1.893000e+03,1.960012e+03,2.046000e+03,2.430000e+03,Tokelau,12.00,10.00,TK,TKL,NaN,0.0118,NaN,189.3000,490.2870,233
233,336,733.0,6.510000e+02,5.960000e+02,5.100000e+02,5.180000e+02,5.423978e+02,5.610000e+02,7.310000e+02,Vatican City,0.44,0.44,VA,VAT,NaN,0.0157,NaN,1177.2727,3049.1364,234

In [46]:
d.to_csv('pop2026.csv')
d.to_excel('pop2026.xlsx')

In [47]:
d.isnull().sum()

place              0
pop1980            0
pop2000            0
pop2010            0
pop2022            0
pop2023            0
pop2026            0
pop2030            0
pop2050            0
country            0
area               0
landAreaKm         0
cca2               1
cca3               0
netChange          8
growthRate         0
worldPercentage    6
density            0
densityMi          0
rank               0
dtype: int64

In [48]:
d.worldPercentage

0      0.1785
1      0.1781
2      0.0425
3      0.0347
4      0.0300
        ...
229       NaN
230       NaN
231       NaN
232       NaN
233       NaN
Name: worldPercentage, Length: 234, dtype: float64

In [50]:
pop23_sum= d.loc[:,'pop2023'].sum()
pop23_sum

8043615390.0

In [54]:
nan_index =d[d.worldPercentage.isnull()].index

In [55]:
nan_index

Index([228, 229, 230, 231, 232, 233], dtype='int64')

In [61]:
nan_fill=(d.loc[nan_index,'pop2023']/pop23_sum)*100
nan_fill

228    0.000073
229    0.000055
230    0.000047
231    0.000024
232    0.000024
233    0.000006
Name: pop2023, dtype: float64

In [62]:
d.loc[nan_index,'worldPercentage']=nan_fill

In [63]:
d.loc[nan_index,:]

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2026,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
228,666,6106.0,6274.0,6052.0,5862.0,5840.0,5773.4240,5651.0,5165.0,Saint Pierre and Miquelon,242.00,242.00,PM,SPM,NaN,-0.0038,0.000073,24.1322,62.5025,229
229,500,11452.0,5138.0,4938.0,4390.0,4386.0,4374.1578,4301.0,3781.0,Montserrat,102.00,102.00,MS,MSR,NaN,-0.0009,0.000055,43.0000,111.3700,230
230,238,2240.0,3080.0,3187.0,3780.0,3791.0,3823.9817,3869.0,3779.0,Falkland Islands,12173.00,12173.00,FK,FLK,NaN,0.0029,0.000047,0.3114,0.8066,231
231,570,3637.0,2074.0,1812.0,1934.0,1935.0,1937.9025,1948.0,2096.0,Niue,261.00,261.00,NU,NIU,0.0,0.0005,0.000024,7.4138,19.2017,232
232,772,1647.0,1666.0,1367.0,1871.0,1893.0,1960.0122,2046.0,2430.0,Tokelau,12.00,10.00,TK,TKL,NaN,0.0118,0.000024,189.3000,490.2870,233
233,336,733.0,651.0,596.0,510.0,518.0,542.3978,561.0,731.0,Vatican City,0.44,0.44,VA,VAT,NaN,0.0157,0.000006,1177.2727,3049.1364,234

In [64]:
d.isnull().sum()

place              0
pop1980            0
pop2000            0
pop2010            0
pop2022            0
pop2023            0
pop2026            0
pop2030            0
pop2050            0
country            0
area               0
landAreaKm         0
cca2               1
cca3               0
netChange          8
growthRate         0
worldPercentage    0
density            0
densityMi          0
rank               0
dtype: int64

In [67]:
net_index= d[d.netChange.isnull()].index 
net_index

Index([217, 221, 227, 228, 229, 230, 232, 233], dtype='int64')

In [70]:
ans= (d.loc[net_index,'pop2023']-d.loc[net_index,'pop2022'])/1000

In [71]:
ans

217   -0.018
221    0.003
227    0.027
228   -0.022
229   -0.004
230    0.011
232    0.022
233    0.008
dtype: float64

In [72]:
d.loc[net_index,'netChange']=ans

In [73]:
d

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2026,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.463343e+09,1.514994e+09,1.670491e+09,India,3287590.00,2973190.00,IN,IND,0.4184,0.0081,0.178500,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.424816e+09,1.415606e+09,1.312636e+09,China,9706961.00,9424702.90,CN,CHN,-0.0113,-0.0002,0.178100,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.450965e+08,3.521623e+08,3.753920e+08,United States,9372610.00,9147420.00,US,USA,0.0581,0.0050,0.042500,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.836954e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.00,1877519.00,ID,IDN,0.0727,0.0074,0.034700,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.547705e+08,2.740298e+08,3.678085e+08,Pakistan,881912.00,770880.00,PK,PAK,0.1495,0.0198,0.030000,311.9625,807.9829,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,500,11452.0,5.138000e+03,4.938000e+03,4.390000e+03,4.386000e+03,4.374158e+03,4.301000e+03,3.781000e+03,Montserrat,102.00,102.00,MS,MSR,-0.0040,-0.0009,0.000055,43.0000,111.3700,230
230,238,2240.0,3.080000e+03,3.187000e+03,3.780000e+03,3.791000e+03,3.823982e+03,3.869000e+03,3.779000e+03,Falkland Islands,12173.00,12173.00,FK,FLK,0.0110,0.0029,0.000047,0.3114,0.8066,231
231,570,3637.0,2.074000e+03,1.812000e+03,1.934000e+03,1.935000e+03,1.937902e+03,1.948000e+03,2.096000e+03,Niue,261.00,261.00,NU,NIU,0.0000,0.0005,0.000024,7.4138,19.2017,232
232,772,1647.0,1.666000e+03,1.367000e+03,1.871000e+03,1.893000e+03,1.960012e+03,2.046000e+03,2.430000e+03,Tokelau,12.00,10.00,TK,TKL,0.0220,0.0118,0.000024,189.3000,490.2870,233
233,336,733.0,6.510000e+02,5.960000e+02,5.100000e+02,5.180000e+02,5.423978e+02,5.610000e+02,7.310000e+02,Vatican City,0.44,0.44,VA,VAT,0.0080,0.0157,0.000006,1177.2727,3049.1364,234

In [74]:
d.isnull().sum()

place              0
pop1980            0
pop2000            0
pop2010            0
pop2022            0
pop2023            0
pop2026            0
pop2030            0
pop2050            0
country            0
area               0
landAreaKm         0
cca2               1
cca3               0
netChange          0
growthRate         0
worldPercentage    0
density            0
densityMi          0
rank               0
dtype: int64

In [80]:
# d.loc[:5,['area','netChange']]

In [81]:
d.loc[net_index,:]

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2026,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
217,674,21346.0,26823.0,31608.0,33660.0,33642.0,33591.5370,33458.0,32044.0,San Marino,61.00,60.00,SM,SMR,-0.018,-0.0005,0.000000,560.7000,1452.2130,218
221,585,12252.0,19726.0,18540.0,18055.0,18058.0,18068.8348,17919.0,16689.0,Palau,459.00,460.00,PW,PLW,0.003,0.0002,0.000000,39.2565,101.6744,222
227,652,2983.0,7082.0,8988.0,10967.0,10994.0,11076.4550,11113.0,10210.0,Saint Barthelemy,21.00,25.00,BL,BLM,0.027,0.0025,0.000000,439.7600,1138.9784,228
228,666,6106.0,6274.0,6052.0,5862.0,5840.0,5773.4240,5651.0,5165.0,Saint Pierre and Miquelon,242.00,242.00,PM,SPM,-0.022,-0.0038,0.000073,24.1322,62.5025,229
229,500,11452.0,5138.0,4938.0,4390.0,4386.0,4374.1578,4301.0,3781.0,Montserrat,102.00,102.00,MS,MSR,-0.004,-0.0009,0.000055,43.0000,111.3700,230
230,238,2240.0,3080.0,3187.0,3780.0,3791.0,3823.9817,3869.0,3779.0,Falkland Islands,12173.00,12173.00,FK,FLK,0.011,0.0029,0.000047,0.3114,0.8066,231
232,772,1647.0,1666.0,1367.0,1871.0,1893.0,1960.0122,2046.0,2430.0,Tokelau,12.00,10.00,TK,TKL,0.022,0.0118,0.000024,189.3000,490.2870,233
233,336,733.0,651.0,596.0,510.0,518.0,542.3978,561.0,731.0,Vatican City,0.44,0.44,VA,VAT,0.008,0.0157,0.000006,1177.2727,3049.1364,234

## Numpy

In [82]:
import numpy as np # pip install numpy

In [83]:
# numpy - numerical python
# arrays - list

In [86]:
a=np.array([12,10,45,33,21])
type(a)

numpy.ndarray

In [87]:
a

array([12, 10, 45, 33, 21])

In [88]:
a.ndim

1

In [89]:
a2=np.array([[12,14,56,7,6,4]])
a2

array([[12, 14, 56,  7,  6,  4]])

In [90]:
a2.ndim

2

In [91]:
a2= np.array([ 
              [1,2,3],
              [5,6,7]
            ])

In [92]:
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [93]:
a3=np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,2],
        [1,8]
    ]
])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 2],
        [1, 8]]])

In [94]:
a3.ndim

3

In [95]:
a

array([12, 10, 45, 33, 21])

In [98]:
a[:4]

array([12, 10, 45, 33])

In [101]:
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [100]:
a2[1]

array([5, 6, 7])

In [102]:
a2[1][1]

6

In [103]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 2],
        [1, 8]]])

In [ ]:
a3[1]

array([[5, 2],
       [1, 8]])

In [106]:
a3[1][1][0]

1

In [ ]:
np.arange(1,15,2) # start stop step

array([ 1,  3,  5,  7,  9, 11, 13])

In [110]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [111]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [112]:
np.array([4 for i in range(0,5)])

array([4, 4, 4, 4, 4])

In [ ]:
np.linspace(1,10,50) # start, stop, number of values (equal gap)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.linspace(0,10,5)  # start stop total number of values

array([ 0. ,  2.5,  5. ,  7.5, 10. ])