### Feature Engineering

<img src="image.png" width="400">

In [55]:
# In cmd  - pip install scikit-learn -- sklearn
# In notebook - !pip install scikit-learn
import pandas as pd

In [56]:
data= pd.DataFrame({'Result':['good','bad','good','bad','excellent','good','good','excellent']})
data

      Result
0       good
1        bad
2       good
3        bad
4  excellent
5       good
6       good
7  excellent

In [57]:
data.Result.map({'good':1,'bad':2,'excellent':3})# map is used to replace the values in the column with the values provided in the dictionary

0    1
1    2
2    1
3    2
4    3
5    1
6    1
7    3
Name: Result, dtype: int64

In [58]:
# label encoder    # it is used to convert the categorical values into numerical values
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()

In [59]:
# fit, transform, fit_transform 
encoder.fit(data.Result)# it is used to fit the data to the encoder

LabelEncoder()

In [60]:
encoder.transform(data.Result)# it is used to transform the data into numerical values

array([2, 0, 2, 0, 1, 2, 2, 1])

In [61]:
data['Label_result']=encoder.transform(data.Result)

In [62]:
data

      Result  Label_result
0       good             2
1        bad             0
2       good             2
3        bad             0
4  excellent             1
5       good             2
6       good             2
7  excellent             1

In [63]:
print(data.Result)

0         good
1          bad
2         good
3          bad
4    excellent
5         good
6         good
7    excellent
Name: Result, dtype: str

In [ ]:
data['Result']=data['Result'].astype('str')
df_pandas_encoded = pd.get_dummies(data, columns=['Result'])#get_dummies is used to convert the categorical values into numerical values by creating new columns for each category and assigning 1 or 0 to indicate the presence or absence of the category in the original column
df_pandas_encoded

In [65]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Result        8 non-null      str
 1   Label_result  8 non-null      int64
dtypes: int64(1), str(1)
memory usage: 260.0 bytes

In [66]:
data['Result']=data['Result'].astype('object')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Result        8 non-null      object
 1   Label_result  8 non-null      int64
dtypes: int64(1), object(1)
memory usage: 260.0+ bytes

In [ ]:
from sklearn.preprocessing import OneHotEncoder

he=OneHotEncoder(sparse_output=False)#sparse_output output ko false karne se hume ek dense array milega jisme 1 aur 0 honge

categorical_columns=data.select_dtypes(include=['object','category']).columns
categorical_columns

Index(['Result'], dtype='str')

In [82]:
encoded=he.fit_transform(data[categorical_columns])

In [69]:
he.get_feature_names_out(categorical_columns)

array(['Result_bad', 'Result_excellent', 'Result_good'], dtype=object)

In [70]:
print(encoded)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]

In [71]:

one_hot_df = pd.DataFrame(encoded, 
                          columns=he.get_feature_names_out(categorical_columns))

In [72]:
one_hot_df

   Result_bad  Result_excellent  Result_good
0         0.0               0.0          1.0
1         1.0               0.0          0.0
2         0.0               0.0          1.0
3         1.0               0.0          0.0
4         0.0               1.0          0.0
5         0.0               0.0          1.0
6         0.0               0.0          1.0
7         0.0               1.0          0.0

In [73]:
pd.concat([data,one_hot_df],axis=1)

      Result  Label_result  Result_bad  Result_excellent  Result_good
0       good             2         0.0               0.0          1.0
1        bad             0         1.0               0.0          0.0
2       good             2         0.0               0.0          1.0
3        bad             0         1.0               0.0          0.0
4  excellent             1         0.0               1.0          0.0
5       good             2         0.0               0.0          1.0
6       good             2         0.0               0.0          1.0
7  excellent             1         0.0               1.0          0.0

In [74]:
df=pd.read_csv('pre-owned cars.csv')
df.head()

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,01-01-2021,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,01-07-2018,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,Manual,2022.0,01-08-2022,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,01-04-2023,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,Manual,2021.0,01-07-2021,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2806 entries, 0 to 2805
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                2805 non-null   str
 1   model                2805 non-null   str
 2   transmission         2805 non-null   str
 3   make_year            2805 non-null   float64
 4   reg_year             720 non-null    str
 5   fuel_type            2805 non-null   str
 6   engine_capacity(CC)  2688 non-null   float64
 7   km_driven            2805 non-null   float64
 8   ownership            2805 non-null   str
 9   price                2806 non-null   int64
 10  overall_cost         2805 non-null   float64
 11  has_insurance        2805 non-null   object
 12  spare_key            2805 non-null   str
 13  reg_number           2805 non-null   str
 14  title                2805 non-null   str
dtypes: float64(4), int64(1), object(1), str(9)
memory usage: 329.0+ KB

In [76]:
df.transmission.value_counts()

transmission
Manual       1925
Automatic     880
Name: count, dtype: int64

In [77]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
a= le.fit_transform(df.transmission)#le.fit_transform(df.loc[:,'transmission'])

In [ ]:
df.insert(loc=4,column='trans',value=a)

In [79]:
df

,brand,model,transmission,make_year,trans,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,1,01-01-2021,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,1,01-07-2018,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,Manual,2022.0,1,01-08-2022,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,0,01-04-2023,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,Manual,2021.0,1,01-07-2021,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2801,Ford,Ecosport TREND + 1.5L PETROL AT,Automatic,2018.0,0,NaN,Petrol,1497.0,46982.0,1st owner,661000,12920.0,True,Yes,MH03,2018 Ford Ecosport TREND + 1.5L PETROL AT
2802,Honda,Jazz 1.2L I-VTEC V,Manual,2015.0,1,NaN,Petrol,1199.0,38706.0,2nd owner,412000,8057.0,True,Yes,MH01,2015 Honda Jazz 1.2L I-VTEC V
2803,Hyundai,Elite i20 MAGNA 1.2,Manual,2016.0,1,NaN,Petrol,1197.0,31405.0,1st owner,496000,9704.0,True,Yes,MH03,2016 Hyundai Elite i20 MAGNA 1.2
2804,Maruti,Baleno DELTA PETROL 1.2,Manual,2017.0,1,NaN,Petrol,1197.0,47676.0,1st owner,509000,9959.0,True,Yes,MH04,2017 Maruti Baleno DELTA PETROL 1.2
2805,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,1883558000,NaN,NaN,NaN,NaN,NaN

In [80]:
df['transmission']=le.fit_transform(df.transmission)

In [81]:
df

,brand,model,transmission,make_year,trans,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,1,2020.0,1,01-01-2021,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,1,2018.0,1,01-07-2018,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,1,2022.0,1,01-08-2022,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,0,2023.0,0,01-04-2023,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,1,2021.0,1,01-07-2021,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2801,Ford,Ecosport TREND + 1.5L PETROL AT,0,2018.0,0,NaN,Petrol,1497.0,46982.0,1st owner,661000,12920.0,True,Yes,MH03,2018 Ford Ecosport TREND + 1.5L PETROL AT
2802,Honda,Jazz 1.2L I-VTEC V,1,2015.0,1,NaN,Petrol,1199.0,38706.0,2nd owner,412000,8057.0,True,Yes,MH01,2015 Honda Jazz 1.2L I-VTEC V
2803,Hyundai,Elite i20 MAGNA 1.2,1,2016.0,1,NaN,Petrol,1197.0,31405.0,1st owner,496000,9704.0,True,Yes,MH03,2016 Hyundai Elite i20 MAGNA 1.2
2804,Maruti,Baleno DELTA PETROL 1.2,1,2017.0,1,NaN,Petrol,1197.0,47676.0,1st owner,509000,9959.0,True,Yes,MH04,2017 Maruti Baleno DELTA PETROL 1.2
2805,NaN,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,1883558000,NaN,NaN,NaN,NaN,NaN