In [100]:
import pandas as pd

In [101]:
df=pd.read_csv("neet_data1.csv")

In [102]:
df.head()

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 47381 entries, 0 to 47380
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   created_at           47381 non-null  str
 1   retweet_count        47381 non-null  int64
 2   source               47362 non-null  str
 3   user_id              47381 non-null  int64
 4   user_name            47380 non-null  str
 5   user_description     36510 non-null  str
 6   user_follower_count  47381 non-null  int64
 7   user_friends_count   47381 non-null  int64
 8   user_location        26247 non-null  str
 9   user_verified        47381 non-null  bool
 10  user_url             9280 non-null   str
 11  tweet                47381 non-null  str
 12  length_of_tweet      47381 non-null  int64
dtypes: bool(1), int64(5), str(7)
memory usage: 4.4 MB

In [104]:
df.shape

(47381, 13)

In [105]:
df.describe()

,retweet_count,user_id,user_follower_count,user_friends_count,length_of_tweet
count,47381.000000,4.738100e+04,4.738100e+04,47381.000000,47381.000000
mean,331.769190,7.851397e+17,2.465465e+04,681.960322,120.293050
std,5146.699757,5.664197e+17,4.153120e+05,2897.910542,35.647986
min,0.000000,1.516830e+05,0.000000e+00,0.000000,4.000000
25%,0.000000,2.906389e+09,1.900000e+01,41.000000,114.000000
50%,6.000000,1.071028e+18,1.200000e+02,218.000000,140.000000
75%,150.000000,1.283824e+18,5.960000e+02,705.000000,140.000000
max,614304.000000,1.325416e+18,1.393436e+07,490801.000000,158.000000

In [106]:
# df.sort_values(by="retweet_count", ascending=False)

In [107]:
result = df.sort_values(by="retweet_count", ascending=False)[
    ["source", "retweet_count", "user_name", "tweet", "created_at", "user_url"]
].head(1)

result

,source,retweet_count,user_name,tweet,created_at,user_url
32860,Twitter for iPhone,614304,\xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3,"RT @JoeBiden: America, I\xe2\x80\x99m honored ...",2020-11-08 05:30:01,https://t.co/cHZdP4uOdu

In [108]:
df["retweet_count"].head(10).sum()

np.int64(866)

In [109]:
df.loc[df["source"] == "Twitter for Android", "retweet_count"].sum()

np.int64(9386742)

In [110]:
result = df.sort_values(by="user_follower_count", ascending=False)[
    ["user_name", "user_location"]
].head(1)

result

      user_name user_location
44367      NDTV         India

In [111]:
# df["followers_friend_ratio"] = df["user_follower_count"] / df["user_friends_count"] 

# df.head()

In [112]:
ff=df["user_follower_count"] / df["user_friends_count"]

In [113]:
df.insert(6, column="followers_friend_ratio", value=ff)
df.head()

,created_at,retweet_count,source,user_id,user_name,user_description,followers_friend_ratio,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,0.077778,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",0.770819,2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",0.281343,285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,0.314775,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,0.083333,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140

In [114]:
df.isnull().sum()

created_at                    0
retweet_count                 0
source                       19
user_id                       0
user_name                     1
user_description          10871
followers_friend_ratio      147
user_follower_count           0
user_friends_count            0
user_location             21134
user_verified                 0
user_url                  38101
tweet                         0
length_of_tweet               0
dtype: int64

In [115]:
df["user_description"] = df["user_description"].fillna("Twitter user")

In [116]:
df

,created_at,retweet_count,source,user_id,user_name,user_description,followers_friend_ratio,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,Twitter user,0.077778,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",0.770819,2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",0.281343,285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,Twitter user,0.314775,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,0.083333,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,0.495127,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,0.030504,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,Twitter user,1.000000,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,0.106952,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,0.355556,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [117]:
df.isnull().sum()

created_at                    0
retweet_count                 0
source                       19
user_id                       0
user_name                     1
user_description              0
followers_friend_ratio      147
user_follower_count           0
user_friends_count            0
user_location             21134
user_verified                 0
user_url                  38101
tweet                         0
length_of_tweet               0
dtype: int64

In [118]:
df.dropna(axis=1, inplace=True)

In [119]:
df

,created_at,retweet_count,user_id,user_description,user_follower_count,user_friends_count,user_verified,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,1250294694937915394,Twitter user,14,180,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,57059492,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,False,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,1016022678,"Wisdom is knowing the right path to take, Inte...",285,1013,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,1085818329816883201,Twitter user,147,467,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,1227501071490113537,it's not my attitude it's my style,2,24,False,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,1168840190426632192,Bhola sa chora,254,513,False,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,1696615807,Random person who likes drawing (but not a \nl...,23,754,False,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,1313330869113745413,Twitter user,2,2,False,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,1161551282995388416,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,False,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,1211810532006612992,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,False,i hate talking to people from my department bu...,139

In [120]:
df.insert(2,"is_allow",True)

In [121]:
df

,created_at,retweet_count,is_allow,user_id,user_description,user_follower_count,user_friends_count,user_verified,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,True,1250294694937915394,Twitter user,14,180,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,True,57059492,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,False,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,True,1016022678,"Wisdom is knowing the right path to take, Inte...",285,1013,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,True,1085818329816883201,Twitter user,147,467,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,True,1227501071490113537,it's not my attitude it's my style,2,24,False,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,True,1168840190426632192,Bhola sa chora,254,513,False,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,True,1696615807,Random person who likes drawing (but not a \nl...,23,754,False,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,True,1313330869113745413,Twitter user,2,2,False,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,True,1161551282995388416,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,False,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,True,1211810532006612992,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,False,i hate talking to people from my department bu...,139

In [122]:

print("final_df")
final_df = df.drop("tweet", axis=1)
final_df

final_df

,created_at,retweet_count,is_allow,user_id,user_description,user_follower_count,user_friends_count,user_verified,length_of_tweet
0,2020-10-31 14:10:28,141,True,1250294694937915394,Twitter user,14,180,False,139
1,2020-10-31 14:10:11,1,True,57059492,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,False,140
2,2020-10-31 14:09:48,141,True,1016022678,"Wisdom is knowing the right path to take, Inte...",285,1013,False,139
3,2020-10-31 14:09:41,141,True,1085818329816883201,Twitter user,147,467,False,139
4,2020-10-31 14:09:22,0,True,1227501071490113537,it's not my attitude it's my style,2,24,False,140
...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,True,1168840190426632192,Bhola sa chora,254,513,False,56
47377,2020-10-30 15:29:35,1700,True,1696615807,Random person who likes drawing (but not a \nl...,23,754,False,74
47378,2020-10-30 15:28:59,167,True,1313330869113745413,Twitter user,2,2,False,140
47379,2020-10-30 15:28:37,270,True,1161551282995388416,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,False,140
47380,2020-10-30 15:28:14,0,True,1211810532006612992,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,False,139

In [124]:

df["created_at"] = df["created_at"].astype(str)
df["year"] = df["created_at"].str.split("-").str[0]
df["month"] = df["created_at"].str.split("-").str[1]
df[["created_at", "month", "year"]]

                created_at month  year
0      2020-10-31 14:10:28    10  2020
1      2020-10-31 14:10:11    10  2020
2      2020-10-31 14:09:48    10  2020
3      2020-10-31 14:09:41    10  2020
4      2020-10-31 14:09:22    10  2020
...                    ...   ...   ...
47376  2020-10-30 15:29:35    10  2020
47377  2020-10-30 15:29:35    10  2020
47378  2020-10-30 15:28:59    10  2020
47379  2020-10-30 15:28:37    10  2020
47380  2020-10-30 15:28:14    10  2020

[47381 rows x 3 columns]