# NLP Natural Language Processing jisme ham human data ko machine data mein convert karna
## Machine data is of the form of Vector Embeddings

In [28]:
# Stop words : is am are . 
# tf-idf vecorizer , count vectorizers
# tokenization
# Stemmin an Lemmatization 
# Bag of Words

In [29]:
import nltk
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')
# nltk.download('punkt_tab')

In [30]:
import pandas as pd
data = {
    "text": [
        "I love this product",
        "This is a 23523@# bad product. This is very poor product",
        "Amazing experience. I would love to buy it again",
        "Worst service ever. donot buy it, i am gonna give it -1 star",
        "I am very $#  happy",
        "I am very disappointed   2    "
    ],
    "label": [1, 0, 1, 0, 1, 0]   # 1 = Positive, 0 = Negative
}

df = pd.DataFrame(data)
df

                                                text  label
0                                I love this product      1
1  This is a 23523@# bad product. This is very po...      0
2   Amazing experience. I would love to buy it again      1
3  Worst service ever. donot buy it, i am gonna g...      0
4                                I am very $#  happy      1
5                     I am very disappointed   2          0

In [31]:
# Text Cleaning

import re

def clean_text(text):
    text = text.lower()                  # lowercase
    text = re.sub(r'[^a-zA-Z]', ' ', text)  # remove punctuation & numbers
    text = re.sub(r'\s+', ' ', text)        # remove extra spaces
    return text

df['clean_text'] = df['text'].apply(clean_text)
print(df[['text', 'clean_text']])

                                                text  \
0                                I love this product
1  This is a 23523@# bad product. This is very po...
2   Amazing experience. I would love to buy it again
3  Worst service ever. donot buy it, i am gonna g...
4                                I am very $#  happy
5                     I am very disappointed   2

                                          clean_text
0                                i love this product
1    this is a bad product this is very poor product
2    amazing experience i would love to buy it again
3  worst service ever donot buy it i am gonna giv...
4                                    i am very happy
5                            i am very disappointed

In [32]:
df

,text,label,clean_text
0,I love this product,1,i love this product
1,This is a 23523@# bad product. This is very po...,0,this is a bad product this is very poor product
2,Amazing experience. I would love to buy it again,1,amazing experience i would love to buy it again
3,"Worst service ever. donot buy it, i am gonna g...",0,worst service ever donot buy it i am gonna giv...
4,I am very $# happy,1,i am very happy
5,I am very disappointed 2,0,i am very disappointed

In [33]:
# Tokenization 
'''  1. Word Tokenization
     2. Sentence Tokenization
     3. Character tokeniztion
'''

from nltk.tokenize import word_tokenize

df['tokens'] = df['clean_text'].apply(word_tokenize)
print(df['tokens'])
df

0                             [i, love, this, product]
1    [this, is, a, bad, product, this, is, very, po...
2    [amazing, experience, i, would, love, to, buy,...
3    [worst, service, ever, donot, buy, it, i, am, ...
4                                 [i, am, very, happy]
5                          [i, am, very, disappointed]
Name: tokens, dtype: object

,text,label,clean_text,tokens
0,I love this product,1,i love this product,"[i, love, this, product]"
1,This is a 23523@# bad product. This is very po...,0,this is a bad product this is very poor product,"[this, is, a, bad, product, this, is, very, po..."
2,Amazing experience. I would love to buy it again,1,amazing experience i would love to buy it again,"[amazing, experience, i, would, love, to, buy,..."
3,"Worst service ever. donot buy it, i am gonna g...",0,worst service ever donot buy it i am gonna giv...,"[worst, service, ever, donot, buy, it, i, am, ..."
4,I am very $# happy,1,i am very happy,"[i, am, very, happy]"
5,I am very disappointed 2,0,i am very disappointed,"[i, am, very, disappointed]"

In [34]:
from nltk.tokenize import sent_tokenize
df['sentence_tokens']=df['clean_text'].apply(sent_tokenize)

In [35]:
print(df['sentence_tokens'])
df

0                                [i love this product]
1    [this is a bad product this is very poor product]
2    [amazing experience i would love to buy it again]
3    [worst service ever donot buy it i am gonna gi...
4                                    [i am very happy]
5                             [i am very disappointed]
Name: sentence_tokens, dtype: object

,text,label,clean_text,tokens,sentence_tokens
0,I love this product,1,i love this product,"[i, love, this, product]",[i love this product]
1,This is a 23523@# bad product. This is very po...,0,this is a bad product this is very poor product,"[this, is, a, bad, product, this, is, very, po...",[this is a bad product this is very poor product]
2,Amazing experience. I would love to buy it again,1,amazing experience i would love to buy it again,"[amazing, experience, i, would, love, to, buy,...",[amazing experience i would love to buy it again]
3,"Worst service ever. donot buy it, i am gonna g...",0,worst service ever donot buy it i am gonna giv...,"[worst, service, ever, donot, buy, it, i, am, ...",[worst service ever donot buy it i am gonna gi...
4,I am very $# happy,1,i am very happy,"[i, am, very, happy]",[i am very happy]
5,I am very disappointed 2,0,i am very disappointed,"[i, am, very, disappointed]",[i am very disappointed]

In [36]:
# charaacter tokenization
a="palwinder"
n=len(a)
l=[]
for i in range(n):
    l.append(a[i])
print(l)

['p', 'a', 'l', 'w', 'i', 'n', 'd', 'e', 'r']

In [37]:
# after getting the cleaned text and proper tokens we will perform the stopwords removal
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['no_stopwords'] = df['tokens'].apply(remove_stopwords)
print(df['no_stopwords'])

0                                      [love, product]
1                        [bad, product, poor, product]
2              [amazing, experience, would, love, buy]
3    [worst, service, ever, donot, buy, gon, na, gi...
4                                              [happy]
5                                       [disappointed]
Name: no_stopwords, dtype: object

In [38]:
df

,text,label,clean_text,tokens,sentence_tokens,no_stopwords
0,I love this product,1,i love this product,"[i, love, this, product]",[i love this product],"[love, product]"
1,This is a 23523@# bad product. This is very po...,0,this is a bad product this is very poor product,"[this, is, a, bad, product, this, is, very, po...",[this is a bad product this is very poor product],"[bad, product, poor, product]"
2,Amazing experience. I would love to buy it again,1,amazing experience i would love to buy it again,"[amazing, experience, i, would, love, to, buy,...",[amazing experience i would love to buy it again],"[amazing, experience, would, love, buy]"
3,"Worst service ever. donot buy it, i am gonna g...",0,worst service ever donot buy it i am gonna giv...,"[worst, service, ever, donot, buy, it, i, am, ...",[worst service ever donot buy it i am gonna gi...,"[worst, service, ever, donot, buy, gon, na, gi..."
4,I am very $# happy,1,i am very happy,"[i, am, very, happy]",[i am very happy],[happy]
5,I am very disappointed 2,0,i am very disappointed,"[i, am, very, disappointed]",[i am very disappointed],[disappointed]

In [39]:
# stemming 
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

def stemming(tokens):
    return [stemmer.stem(word) for word in tokens]

df['stemmed'] = df['no_stopwords'].apply(stemming)
print(df['stemmed'])

0                                      [love, product]
1                        [bad, product, poor, product]
2                     [amaz, experi, would, love, buy]
3    [worst, servic, ever, donot, buy, gon, na, giv...
4                                              [happi]
5                                         [disappoint]
Name: stemmed, dtype: object

In [40]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatization(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

df['lemmatized'] = df['no_stopwords'].apply(lemmatization)
print(df['lemmatized'])

0                                      [love, product]
1                        [bad, product, poor, product]
2              [amazing, experience, would, love, buy]
3    [worst, service, ever, donot, buy, gon, na, gi...
4                                              [happy]
5                                       [disappointed]
Name: lemmatized, dtype: object

In [41]:
df['final_text'] = df['lemmatized'].apply(lambda x: " ".join(x))
print(df['final_text'])

0                                     love product
1                         bad product poor product
2                amazing experience would love buy
3    worst service ever donot buy gon na give star
4                                            happy
5                                     disappointed
Name: final_text, dtype: str

In [42]:
df

,text,label,clean_text,tokens,sentence_tokens,no_stopwords,stemmed,lemmatized,final_text
0,I love this product,1,i love this product,"[i, love, this, product]",[i love this product],"[love, product]","[love, product]","[love, product]",love product
1,This is a 23523@# bad product. This is very po...,0,this is a bad product this is very poor product,"[this, is, a, bad, product, this, is, very, po...",[this is a bad product this is very poor product],"[bad, product, poor, product]","[bad, product, poor, product]","[bad, product, poor, product]",bad product poor product
2,Amazing experience. I would love to buy it again,1,amazing experience i would love to buy it again,"[amazing, experience, i, would, love, to, buy,...",[amazing experience i would love to buy it again],"[amazing, experience, would, love, buy]","[amaz, experi, would, love, buy]","[amazing, experience, would, love, buy]",amazing experience would love buy
3,"Worst service ever. donot buy it, i am gonna g...",0,worst service ever donot buy it i am gonna giv...,"[worst, service, ever, donot, buy, it, i, am, ...",[worst service ever donot buy it i am gonna gi...,"[worst, service, ever, donot, buy, gon, na, gi...","[worst, servic, ever, donot, buy, gon, na, giv...","[worst, service, ever, donot, buy, gon, na, gi...",worst service ever donot buy gon na give star
4,I am very $# happy,1,i am very happy,"[i, am, very, happy]",[i am very happy],[happy],[happi],[happy],happy
5,I am very disappointed 2,0,i am very disappointed,"[i, am, very, disappointed]",[i am very disappointed],[disappointed],[disappoint],[disappointed],disappointed

In [43]:
df.drop(columns=['text','clean_text','tokens','sentence_tokens','no_stopwords','stemmed','lemmatized'])

   label                                     final_text
0      1                                   love product
1      0                       bad product poor product
2      1              amazing experience would love buy
3      0  worst service ever donot buy gon na give star
4      1                                          happy
5      0                                   disappointed

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X = cv.fit_transform(df['final_text']).toarray()
y = df['label']

print("Vocabulary:", cv.vocabulary_)
print("Feature Matrix:\n", X)

Vocabulary: {'love': 10, 'product': 13, 'bad': 1, 'poor': 12, 'amazing': 0, 'experience': 6, 'would': 17, 'buy': 2, 'worst': 16, 'service': 14, 'ever': 5, 'donot': 4, 'gon': 8, 'na': 11, 'give': 7, 'star': 15, 'happy': 9, 'disappointed': 3}
Feature Matrix:
 [[0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0]
 [1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1]
 [0 0 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

In [45]:
#TF-IDF vectorizer === Termed Frequency Inverse document frequency vectorizer

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['final_text']).toarray()

In [46]:
print(X)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.70710678 0.
  0.         0.70710678 0.         0.         0.         0.        ]
 [0.         0.46177217 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.46177217 0.75731957 0.         0.         0.         0.        ]
 [0.47974754 0.         0.39339985 0.         0.         0.
  0.47974754 0.         0.         0.         0.39339985 0.
  0.         0.         0.         0.         0.         0.47974754]
 [0.         0.         0.27845254 0.         0.33957035 0.33957035
  0.         0.33957035 0.33957035 0.         0.         0.33957035
  0.         0.         0.33957035 0.33957035 0.33957035 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]]

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,df.label,test_size=0.2)

In [48]:
x_train

array([[0.        , 0.        , 0.27845254, 0.        , 0.33957035,
        0.33957035, 0.        , 0.33957035, 0.33957035, 0.        ,
        0.        , 0.33957035, 0.        , 0.        , 0.33957035,
        0.33957035, 0.33957035, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.70710678, 0.        , 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]])

In [49]:
lr=LogisticRegression()

In [50]:
lr.fit(x_train,y_train)

LogisticRegression()

In [51]:
y_test

1    0
2    1
Name: label, dtype: int64

In [52]:
y_pred=lr.predict(x_test)

In [53]:
y_pred

array([1, 1])

In [ ]:
querry=input("User inputL: ")


def predict(querry):
    querry=clean_text(querry)
    tokens=word_tokenize(querry)
    # stop words removal

    lematized=' '.join([lemmatizer])
    # vectorizer
    # prediction 
    #return predicted value